# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rescue_bot/camera_config.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class camera_config(genpy.Message):
  _md5sum = "d706ca6804416e58885c51a33d760341"
  _type = "rescue_bot/camera_config"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 scale
int16 fram_rate
bool color_set"""
  __slots__ = ['scale','fram_rate','color_set']
  _slot_types = ['int16','int16','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       scale,fram_rate,color_set

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(camera_config, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.scale is None:
        self.scale = 0
      if self.fram_rate is None:
        self.fram_rate = 0
      if self.color_set is None:
        self.color_set = False
    else:
      self.scale = 0
      self.fram_rate = 0
      self.color_set = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2hB().pack(_x.scale, _x.fram_rate, _x.color_set))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.scale, _x.fram_rate, _x.color_set,) = _get_struct_2hB().unpack(str[start:end])
      self.color_set = bool(self.color_set)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2hB().pack(_x.scale, _x.fram_rate, _x.color_set))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.scale, _x.fram_rate, _x.color_set,) = _get_struct_2hB().unpack(str[start:end])
      self.color_set = bool(self.color_set)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2hB = None
def _get_struct_2hB():
    global _struct_2hB
    if _struct_2hB is None:
        _struct_2hB = struct.Struct("<2hB")
    return _struct_2hB
